In [1]:
!pip install -q pyomo   #install pyomo

     |████████████████████████████████| 9.7 MB 7.4 MB/s 
     |████████████████████████████████| 49 kB 4.5 MB/s 


In [2]:
from pyomo.environ import * 

In [3]:
import numpy as np    #import numpy

In [4]:
import pandas as pd       #import pandas

For more on pandas library please check https://pandas.pydata.org/pandas-docs/version/0.15/tutorials.html

In [5]:
data_txtfile = np.loadtxt('lab6_ex2.txt')     #load the data

In [6]:
print(data_txtfile)

[[21. 25. 18. 19. 23. 24. 16. 17. 21. 23. 19. 21.]
 [19. 22. 19. 19. 23. 21. 15. 20. 16. 17. 17. 24.]
 [21. 19. 20. 18. 22. 24. 14. 16. 18. 16. 20. 24.]
 [19. 22. 17. 17. 22. 22. 18. 18. 20. 21. 23. 23.]
 [18. 22. 15. 15. 23. 23. 21. 25. 24. 19. 21. 23.]
 [23. 19. 19. 14. 24. 21. 23. 21. 20. 20. 22. 19.]
 [21. 16. 27. 17. 26. 27. 16. 19. 24. 20. 20. 23.]
 [22. 17. 21. 15. 23. 24. 24. 20. 22. 19. 23. 21.]
 [23. 24. 18. 19. 22. 23. 21. 18. 23. 15. 25. 21.]
 [18. 21. 21. 18. 26. 24. 18. 17. 18. 20. 21. 20.]
 [19. 12. 21. 19. 23. 20. 22. 19. 17. 19. 20. 24.]
 [18. 22. 24. 17. 21. 28. 18. 16. 22. 24. 25. 24.]]


In [7]:
# create a model
model_lab6_ex2 = ConcreteModel()

In [8]:
M, N = data_txtfile.shape #we declare a Python variables M, N denoting the factory number and location number respectively
print('Number of rows: ', M)
print('Number of columns: ', N)

Number of rows:  12
Number of columns:  12


In [9]:
row_indices = range(M)
col_indices = range(N)

print(row_indices)
print(col_indices)

range(0, 12)
range(0, 12)


In [10]:
#to get the contents of costs alone from the file we use the following
for row_idx in row_indices:
  for col_idx in col_indices:
    print('cost[',row_idx,'][',col_idx,']:',data_txtfile[row_idx, col_idx])

cost[ 0 ][ 0 ]: 21.0
cost[ 0 ][ 1 ]: 25.0
cost[ 0 ][ 2 ]: 18.0
cost[ 0 ][ 3 ]: 19.0
cost[ 0 ][ 4 ]: 23.0
cost[ 0 ][ 5 ]: 24.0
cost[ 0 ][ 6 ]: 16.0
cost[ 0 ][ 7 ]: 17.0
cost[ 0 ][ 8 ]: 21.0
cost[ 0 ][ 9 ]: 23.0
cost[ 0 ][ 10 ]: 19.0
cost[ 0 ][ 11 ]: 21.0
cost[ 1 ][ 0 ]: 19.0
cost[ 1 ][ 1 ]: 22.0
cost[ 1 ][ 2 ]: 19.0
cost[ 1 ][ 3 ]: 19.0
cost[ 1 ][ 4 ]: 23.0
cost[ 1 ][ 5 ]: 21.0
cost[ 1 ][ 6 ]: 15.0
cost[ 1 ][ 7 ]: 20.0
cost[ 1 ][ 8 ]: 16.0
cost[ 1 ][ 9 ]: 17.0
cost[ 1 ][ 10 ]: 17.0
cost[ 1 ][ 11 ]: 24.0
cost[ 2 ][ 0 ]: 21.0
cost[ 2 ][ 1 ]: 19.0
cost[ 2 ][ 2 ]: 20.0
cost[ 2 ][ 3 ]: 18.0
cost[ 2 ][ 4 ]: 22.0
cost[ 2 ][ 5 ]: 24.0
cost[ 2 ][ 6 ]: 14.0
cost[ 2 ][ 7 ]: 16.0
cost[ 2 ][ 8 ]: 18.0
cost[ 2 ][ 9 ]: 16.0
cost[ 2 ][ 10 ]: 20.0
cost[ 2 ][ 11 ]: 24.0
cost[ 3 ][ 0 ]: 19.0
cost[ 3 ][ 1 ]: 22.0
cost[ 3 ][ 2 ]: 17.0
cost[ 3 ][ 3 ]: 17.0
cost[ 3 ][ 4 ]: 22.0
cost[ 3 ][ 5 ]: 22.0
cost[ 3 ][ 6 ]: 18.0
cost[ 3 ][ 7 ]: 18.0
cost[ 3 ][ 8 ]: 20.0
cost[ 3 ][ 9 ]: 21.0
cost[ 3 ][ 10 ]: 23.0
cost[ 

In [11]:
#declare the decision variables in the model
model_lab6_ex2.x = Var(row_indices, col_indices, domain= NonNegativeIntegers)

In [12]:
#declare the objective function
model_lab6_ex2.objective = Objective(expr=sum(data_txtfile[i,j]*model_lab6_ex2.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

In [13]:
#declare the constraints
model_lab6_ex2.constraints = ConstraintList()

In [14]:
#now we will add the constraints for the factories first
model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[0,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[1,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[2,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[3,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[4,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[5,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[6,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[7,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[8,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[9,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[10,j] for j in col_indices) == 1) 

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[11,j] for j in col_indices) == 1) 

In [15]:
#Now we will add few another constraints for locations
model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,0] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,1] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,2] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,3] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,4] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,5] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,6] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,7] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,8] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,9] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,10] for i in row_indices) == 1)

model_lab6_ex2.constraints.add(expr=sum(model_lab6_ex2.x[i,11] for i in row_indices) == 1)

In [16]:
model_lab6_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11

In [17]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155569 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [18]:
opt_cbc = SolverFactory('cbc')

In [19]:
result = opt_cbc.solve(model_lab6_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [20]:
# display solution
print('\nObjective = ', model_lab6_ex2.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6_ex2.x[i, j].value == 1:
      print('Factory', i+1, 'is to be located at', j+1)

print('\nConstraints')
model_lab6_ex2.constraints.display()


Objective =  204.0

Decision Variables
Factory 1 is to be located at 11
Factory 2 is to be located at 9
Factory 3 is to be located at 8
Factory 4 is to be located at 6
Factory 5 is to be located at 3
Factory 6 is to be located at 12
Factory 7 is to be located at 7
Factory 8 is to be located at 4
Factory 9 is to be located at 10
Factory 10 is to be located at 1
Factory 11 is to be located at 2
Factory 12 is to be located at 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 

In [21]:
#change the domain to nonnegativereals
for i in row_indices:
  for j in col_indices:
    model_lab6_ex2.x[i, j].domain=NonNegativeReals

In [22]:
model_lab6_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11

In [23]:
result = opt_cbc.solve(model_lab6_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [24]:
# display solution
print('\nObjective = ', model_lab6_ex2.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6_ex2.x[i, j].value == 1:
      print('Factory', i+1, 'is to be located at', j+1)

print('\nConstraints')
model_lab6_ex2.constraints.display()


Objective =  204.0

Decision Variables
Factory 1 is to be located at 11
Factory 2 is to be located at 9
Factory 3 is to be located at 8
Factory 4 is to be located at 6
Factory 5 is to be located at 3
Factory 6 is to be located at 12
Factory 7 is to be located at 7
Factory 8 is to be located at 4
Factory 9 is to be located at 10
Factory 10 is to be located at 1
Factory 11 is to be located at 2
Factory 12 is to be located at 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 

In [25]:
#change in the txt file
data_txtfile[2, 3] = 200000000
data_txtfile[8, 6] = 300000000
data_txtfile[3, 9] = 200000000

In [26]:
#again change the domain to it's original form
for i in row_indices:
  for j in col_indices:
    model_lab6_ex2.x[i, j].domain=NonNegativeIntegers

In [27]:
model_lab6_ex2.objective = Objective(expr=sum(data_txtfile[i,j]*model_lab6_ex2.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [28]:
model_lab6_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11

In [29]:
result = opt_cbc.solve(model_lab6_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [30]:
# display solution
print('\nObjective = ', model_lab6_ex2.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6_ex2.x[i, j].value == 1:
      print('Factory', i+1, 'is to be located at', j+1)

print('\nConstraints')
model_lab6_ex2.constraints.display()


Objective =  204.0

Decision Variables
Factory 1 is to be located at 11
Factory 2 is to be located at 9
Factory 3 is to be located at 8
Factory 4 is to be located at 6
Factory 5 is to be located at 3
Factory 6 is to be located at 12
Factory 7 is to be located at 7
Factory 8 is to be located at 4
Factory 9 is to be located at 10
Factory 10 is to be located at 1
Factory 11 is to be located at 2
Factory 12 is to be located at 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 

In [31]:
#we will now put some real values of cost 
data_txtfile[2, 4] = 22.67
data_txtfile[5, 6] = 21.83
data_txtfile[3, 7] = 17.78

In [32]:
model_lab6_ex2.objective = Objective(expr=sum(data_txtfile[i,j]*model_lab6_ex2.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [33]:
result = opt_cbc.solve(model_lab6_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [34]:
# display solution
print('\nObjective = ', model_lab6_ex2.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6_ex2.x[i, j].value == 1:
      print('Factory', i+1, 'is to be located at', j+1)

print('\nConstraints')
model_lab6_ex2.constraints.display()


Objective =  204.0

Decision Variables
Factory 1 is to be located at 11
Factory 2 is to be located at 9
Factory 3 is to be located at 8
Factory 4 is to be located at 6
Factory 5 is to be located at 3
Factory 6 is to be located at 12
Factory 7 is to be located at 7
Factory 8 is to be located at 4
Factory 9 is to be located at 10
Factory 10 is to be located at 1
Factory 11 is to be located at 2
Factory 12 is to be located at 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 

**Report on Exercise 2 part 1:**

The LP formulation of the given problem is as follows:

$ min \sum_{i=1}^n\sum_{j=1}^n C(i,j)*x_{ij} $

$s.t. \sum_{i=1}^nx_{ij}=1 ∀iϵ${ 1,2,....n }

$ \sum_{j=1}^nx_{ij} <= 1  ∀ jϵ${1,2,....n}

$ x_{ij}>= 0 ∀i,j ϵ$ {1,2,....,n}

where C(i, j) is the cost of locating factory i to location j and $x_{ij}$ is the indicator variable which indicates that whether the factory i is located to location j or not.

**Report on Exercise 2 part 8:**

**Objective** =  204.0

**Decision Variables:**

Factory 1 is to be located at 11

Factory 2 is to be located at 9

Factory 3 is to be located at 8

Factory 4 is to be located at 6

Factory 5 is to be located at 3

Factory 6 is to be located at 12

Factory 7 is to be located at 7

Factory 8 is to be located at 4

Factory 9 is to be located at 10

Factory 10 is to be located at 1

Factory 11 is to be located at 2

Factory 12 is to be located at 5

**Constraints**

constraints : Size=24

    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 :  1.0 :   1.0
     20 :   1.0 :  1.0 :   1.0
     21 :   1.0 :  1.0 :   1.0
     22 :   1.0 :  1.0 :   1.0
     23 :   1.0 :  1.0 :   1.0
     24 :   1.0 :  1.0 :   1.0

**Report on Exercise 2 part 9:**

The new solution after changing the domain to NonNegativeReals is as follows:

**Objective** =  204.0

**Decision Variables:**

Factory 1 is to be located at 11

Factory 2 is to be located at 9

Factory 3 is to be located at 8

Factory 4 is to be located at 6

Factory 5 is to be located at 3

Factory 6 is to be located at 12

Factory 7 is to be located at 7

Factory 8 is to be located at 4

Factory 9 is to be located at 10

Factory 10 is to be located at 1

Factory 11 is to be located at 2

Factory 12 is to be located at 5

**Constraints**

constraints : Size=24

    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 :  1.0 :   1.0
     20 :   1.0 :  1.0 :   1.0
     21 :   1.0 :  1.0 :   1.0
     22 :   1.0 :  1.0 :   1.0
     23 :   1.0 :  1.0 :   1.0
     24 :   1.0 :  1.0 :   1.0

**Report on Exercise 2 part 10:**

Yes, after changing the domain variables from NonNegativeIntegers to NonNegativeReals, the optimal cost and solution is same. This is because we can locate only one factory to a location and assigning the fractional values to the decision variables may not lead to the minimum cost. It will increase the total cost i.e., the solution would not remain optimal anymore.

**Report on Exercise 2 part 12:**

Since facility 3, 9 and 6 can not be located at locations 4, 6 and 10 respectively so, I'll make changes in the lab6_ex2.txt file.

I'll increase the cost of locating the given facilities(3,9,6) at the given locations(4,6,10) respectively in such a way that if Factory 3 is assigned to location 4 initially then it got changed and similarly with the other two factories.

**The solution after these changes is as follows:**

**Objective** =  204.0

**Decision Variables:**

Factory 1 is to be located at 11

Factory 2 is to be located at 9

Factory 3 is to be located at 8

Factory 4 is to be located at 6

Factory 5 is to be located at 3

Factory 6 is to be located at 12

Factory 7 is to be located at 7

Factory 8 is to be located at 4

Factory 9 is to be located at 10

Factory 10 is to be located at 1

Factory 11 is to be located at 2

Factory 12 is to be located at 5

**Constraints**

constraints : Size=24

    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 :  1.0 :   1.0
     20 :   1.0 :  1.0 :   1.0
     21 :   1.0 :  1.0 :   1.0
     22 :   1.0 :  1.0 :   1.0
     23 :   1.0 :  1.0 :   1.0
     24 :   1.0 :  1.0 :   1.0


**Observations from the result:**

After changing the file according to the given condition i.e., increasing the costs, I observed that the optimal solution is exactly the same i.e., the factories are still assigned to the same location with the same total cost because these factories (3, 9, 6) already were not located to the given locations i.e., 4, 6 and 10.

